fix: unset QT_LOGGING_RULES on deepin
linuxdeepin/startdde pull request #104
Opened 2022-04-29 08:37 UTC by tsic404

QT_LOGGING_RULES influence qt dev on deepin,
now unset QT_LOGGING_RULES on deepin

Log: unset QT_LOGGING_RULES on deepin

2022-05-05 01:29 UTC, zccrs reviewed
/+1

2022-05-05 01:30 UTC, zccrs requested changes

2022-05-05 01:30 UTC, zccrs commented on misc/Xsession.d/00deepin-dde-env
> +    if [ ! `grep Community /etc/os-version` ];then
得考虑下其它发行版

2022-05-11 11:31 UTC, zccrs reviewed
+1

2022-05-27 02:05 UTC, justforlxz approved these changes

2022-05-27 03:17 UTC, zccrs approved these changes

2022-05-27 03:18 UTC, merged