fix: 教育版合入主线: 使用显卡驱动管理器安装闭源驱动后，在1920x1080分辨率下切换为60.05Hz、60Hz、50.04Hz刷…
linuxdeepin/startdde pull request #183
Opened 2022-11-25 07:34 UTC by wuhaizhou2003

…新率，屏幕有闪烁现象

使用显卡驱动管理器安装闭源驱动后，在1920x1080分辨率下切换为60.05Hz、60Hz、50.04Hz刷新率，屏幕有闪烁现象

Log: 使用显卡驱动管理器安装闭源驱动后，在1920x1080分辨率下切换为60.05Hz、60Hz、50.04Hz刷新率，屏幕有闪烁现象
Bug: https://pms.uniontech.com/bug-view-107072.html
Influence: 控制中心-显示-分辨率

2022-12-02 08:01 UTC, Groveer commented
+1

2022-12-05 03:42 UTC, KT-lcz approved these changes

2022-12-05 03:46 UTC, KT-lcz requested changes
点击错误，去掉approve

2022-12-06 07:26 UTC, Groveer commented on display/xorg.go
> +		if (mode.ModeFlags & randr.ModeFlagDoubleScan) != 0 ||
这个判断放在dde-daemon是不是更好一点 控制中心毕竟是前端应用

2022-12-08 01:29 UTC, closed without merging