feat: 允许用户通过 force-scale-factor.ini 强制设置全局缩放
linuxdeepin/startdde pull request #222
Opened 2023-04-23 08:21 UTC by debuggerx01

当前启动时会根据分辨率最小的屏幕设置全局缩放，这在某些场景下可能并不是用户想要的，比如用户有个高分屏是主屏幕，还有一个低分屏只用来看点简单的信息，当前的模式就会导致用户的主屏也无法正常以全局缩放模式正常使用。 该PR允许用户编辑`~/.config/deepin/force-scale-factor.ini`为如下内容，强制系统的全局缩放：
```
[ForceScaleFactor]
scale=1.5
```

Log: 允许用户通过 force-scale-factor.ini 强制设置全局缩放

2023-04-23 10:00 UTC, xzl01 commented
依稀记得说是在x11下如果不同显示器设置不同缩放比例会导致问题，不知道上游是否解决。anyway，感谢你对于deepin的支持，我们将在研究之后确定是否要合并入这个代码。CC@BLumia

2023-04-23 10:07 UTC, BLumia reviewed
这个修改本地测试过了吗？应该是没有效果的呀

2023-04-23 10:36 UTC, debuggerx01 commented
> 依稀记得说是在x11下如果不同显示器设置不同缩放比例会导致问题，不知道上游是否解决。anyway，感谢你对于deepin的支持，我们将在研究之后确定是否要合并入这个代码。CC@BLumia

不是在给不同的屏幕设置不同的缩放，这是做不到的。这个PR是允许强制设置缩放的值，避免之前的逻辑中自动根据屏幕分辨率设置缩放值在某些场景下不符合预期的问题

2023-04-23 10:38 UTC, debuggerx01 commented
> 这个修改本地测试过了吗？应该是没有效果的呀

我自己机器上测试通过的，不过设置的时候得通过dbus来修改，见帖子中的说明：
[分享让用户可以自己强制指定系统缩放的方法](https://bbs.deepin.org/post/255588)

2023-04-23 10:49 UTC, debuggerx01 commented
> 这个修改本地测试过了吗？应该是没有效果的呀

不过我是在20.9，4K显示器，X11下测试的。

2023-04-24 02:07 UTC, xzl01 commented
> > 依稀记得说是在x11下如果不同显示器设置不同缩放比例会导致问题，不知道上游是否解决。anyway，感谢你对于deepin的支持，我们将在研究之后确定是否要合并入这个代码。CC@BLumia
> 
> 不是在给不同的屏幕设置不同的缩放，这是做不到的。这个PR是允许强制设置缩放的值，避免之前的逻辑中自动根据屏幕分辨率设置缩放值在某些场景下不符合预期的问题 @xzl01

明白你的意思了，就是说原来我们对1080p屏幕缩放限制在1.25以内，现在是解除这个缩放限制对吗？让1080p屏幕也能开到两倍缩放

2023-04-24 02:13 UTC, debuggerx01 commented
> > > 依稀记得说是在x11下如果不同显示器设置不同缩放比例会导致问题，不知道上游是否解决。anyway，感谢你对于deepin的支持，我们将在研究之后确定是否要合并入这个代码。CC@BLumia
> > 
> > 
> > 不是在给不同的屏幕设置不同的缩放，这是做不到的。这个PR是允许强制设置缩放的值，避免之前的逻辑中自动根据屏幕分辨率设置缩放值在某些场景下不符合预期的问题 @xzl01
> 
> 明白你的意思了，就是说原来我们对1080p屏幕缩放限制在1.25以内，现在是解除这个缩放限制对吗？让1080p屏幕也能开到两倍缩放

可以这样理解。
对我来说最大的问题就是，现在一旦插了个1080p的扩展屏，我的4K主屏幕就没法看了

2023-04-29 02:14 UTC, xzl01 commented
我认为合并没有问题 @BLumia 可以联系相关研发审核代码了

2023-05-04 02:36 UTC, dengbo11 requested changes

2023-05-04 02:36 UTC, dengbo11 commented on display/xorg.go
> +
这一段可以封装为一个函数(放到display包中的manager.go中), 在xorg.go中可直接调用,在wl_display包中可通过m 对象去调用

2023-05-04 02:36 UTC, dengbo11 commented on display/xorg.go
> +	filename := getForceScaleFactorFile()
filename -> fileName

2023-05-04 02:36 UTC, dengbo11 commented on display/xorg.go
> +
可放到display manager.go中去, 那样就不用在wl_display包中去定义一个相同的函数了

2023-05-09 07:20 UTC, Decodetalkers commented
ping, @debuggerx01 如果可以的话我们下个版本带上，维护的开发者给你建议了

2023-05-09 12:15 UTC, debuggerx01 commented
> ping, @debuggerx01 如果可以的话我们下个版本带上，维护的开发者给你建议了

最近工作比较忙，有空马上处理建议

2023-05-10 01:11 UTC, debuggerx01 commented on display/xorg.go
> +	filename := getForceScaleFactorFile()
> filename -> fileName

这里命名时我参考了已有的代码，发现除了startmanager.go中有一处使用的是fileName，其他所有地方的命名都是filename，所以确定要改吗？

2023-05-10 01:56 UTC, Decodetalkers commented on display/xorg.go
> +
> > 这一段可以封装为一个函数(放到display包中的manager.go中), 在xorg.go中可直接调用,在wl_display包中可通过m 对象去调用
> 
> 刚试了下把代码放到display包中的manager.go中，xorg.go中确实可直接调用，但在wl_display包中调不到，看上去wl_display包中的Manager定义在wl_display/manager.go中，与display包中的manager.go定义的Manager不是同一个，应该是不行的吧？ 我没学过go，代码都是参考已有代码写出来的，不确定是不是理解有误

你要把display import进来啊

2023-05-10 01:58 UTC, Decodetalkers commented on display/xorg.go
> +	filename := getForceScaleFactorFile()
> > filename -> fileName
> 
> 这里命名时我参考了已有的代码，发现除了startmanager.go中有一处使用的是fileName，其他所有地方的命名都是filename，所以确定要改吗？

其他地方是历史遗留啦，命名风格需要统一成驼峰

2023-05-10 02:47 UTC, debuggerx01 commented
@dengbo11 按照建议修改了，但是现在提交信息检查不通过，请问如何解决？

2023-05-10 02:56 UTC, Decodetalkers commented
你不能搞出5个Commit的，要rebase不是merge，处理成一个commit

2023-05-10 02:57 UTC, Decodetalkers commented on wl_display/manager.go
> +	x_display "github.com/linuxdeepin/startdde/display"
不是Xdisplay，你命名成这个名字那意思是只有x可以用？叫display不重命名就好了

2023-05-10 02:59 UTC, Decodetalkers commented
commit lint这边的要求是

feat:   xxxx

Describe

Log: what is done in this pr

2023-05-10 03:22 UTC, debuggerx01 commented
> commit lint这边的要求是
> 
> feat: xxxx
> 
> Describe
> 
> Log: what is done in this pr

好的，应该解决了

2023-05-10 03:23 UTC, Decodetalkers commented
rebase 下，如果是github ui,是updatebranch,选择rebase,而不是merge

2023-05-10 03:29 UTC, Decodetalkers commented on display/manager.go
> +	return 0.0, fmt.Errorf("no valid force-scale-factor")
不应该返回0 ，应该是原本的缩放

2023-05-10 03:30 UTC, BLumia commented
等有有效的 approval 后，rebase 没冲突的话，我们主动以 rebase 形式合入就 ok。

目前 startdde 看上去也有其它待合入的 PR，就不反复让贡献者点 rebase 了。

2023-05-10 03:31 UTC, debuggerx01 commented on display/manager.go
> +	return 0.0, fmt.Errorf("no valid force-scale-factor")
原本的缩放？1.0吗？我以为这里返回了error就可以了

2023-05-10 03:33 UTC, Decodetalkers commented on display/manager.go
> +	return 0.0, fmt.Errorf("no valid force-scale-factor")
返回1.0吧

2023-05-10 03:33 UTC, Decodetalkers commented on display/manager.go
> +	return 0.0, fmt.Errorf("no valid force-scale-factor")
毕竟这里要阅读代码看到0.0会有困扰

2023-05-10 03:42 UTC, debuggerx01 commented on display/manager.go
> +	return 0.0, fmt.Errorf("no valid force-scale-factor")
> 返回1.0吧

Done

2023-05-10 03:42 UTC, Decodetalkers commented
cc @dengbo11

2023-05-10 05:47 UTC, dengbo11 approved these changes

2023-05-10 05:47 UTC, merged