chore: release dde-daemon 6.0.9.1
linuxdeepin/startdde pull request #242
Opened 2023-09-05 02:57 UTC by BLumia

发布 dde-daemon 6.0.9.1

Log:

2023-09-05 02:59 UTC, BLumia commented
/integrate

2023-09-05 03:07 UTC, tsic404 requested changes
release startdde

2023-09-05 03:36 UTC, tsic404 approved these changes

2023-09-05 05:18 UTC, wineee commented
https://github.com/linuxdeepin/startdde/pull/237 什么时候处理

2023-09-05 06:29 UTC, BLumia commented
> #237 什么时候处理

合入了，已 rebase 此 PR 并将重新提交集成。

2023-09-05 06:29 UTC, BLumia commented
/integrate

2023-09-06 05:39 UTC, tsic404 approved these changes

2023-09-06 05:43 UTC, merged